create database if not exists company_db;
show databases;
use company_db;
create table employees (emp_id int, employee_name varchar(50), department varchar(50), salary int);
describe employees;
alter table employees add column email varchar(100);
alter table employees add column joining_date date;
describe employees;
alter table employees modify column employee_name varchar(100);
alter table employees change column employee_name emp_name varchar(100);
alter table employees add primary key (emp_id);
alter table employees add unique (email);
alter table employees add constraint chk_salary check (salary > 10000);
rename table employees to employee_details;
create table departments (dept_id int);
alter table departments add column dept_name varchar(100);
show tables;
drop table if exists departments;
show tables;
drop table if exists employee_details;

create table employees (emp_id int primary key, emp_name varchar(100), department varchar(50), salary int, email varchar(100) unique, joining_date date, constraint chk_salary check (salary > 10000));
insert into employees values (101, 'arjun', 'it', 48000, 'arjun@company.com', '2024-02-01');
insert into employees values (102, 'neha', 'hr', 52000, 'neha@company.com', '2024-03-15');
insert into employees (emp_id, emp_name, department, salary, email, joining_date) values (103, 'sarthak', 'finance', 61000, 'sarthak@company.com', '2024-04-20'), (104, 'ravi', 'marketing', 45000, 'ravi@company.com', '2024-01-10'), (105, 'tanya', 'sales', 47000, 'tanya@company.com', '2024-05-05');
insert into employees values (106, 'isha', 'it', 53000, 'isha@company.com', '2024-06-12');
insert into employees values (107, 'priya', 'hr', 49000, 'priya@company.com', '2024-07-18');
insert into employees values (108, 'aman', 'finance', 56000, 'aman@company.com', '2024-08-25');
insert into employees values (109, 'sana', 'marketing', 44000, 'sana@company.com', '2024-09-30');
insert into employees values (110, 'karan', 'sales', 42000, 'karan@company.com', '2024-10-02');
update employees set salary = 51000 where emp_id = 101;
update employees set department = 'marketing' where emp_id = 105;
update employees set email = 'sarthak.p@company.com' where emp_id = 103;
update employees set salary = salary + 5000 where department = 'it';
update employees set salary = salary * 1.1 where department = 'hr';
update employees set department = 'marketing' where department = 'sales';
delete from employees where emp_id = 110;
delete from employees where department = 'finance';
insert into employees values (111, 'varun', 'finance', 58000, 'varun@company.com', '2024-11-11'), (112, 'neeraj', 'finance', 47000, 'neeraj@company.com', '2024-12-01');
delete from employees where salary < 45000;
update employees set salary = salary + 3000 where department = 'marketing';
delete from employees;

insert into employees values (201, 'samira', 'it', 62000, 'samira@company.com', '2025-01-10'), (202, 'rishi', 'hr', 55000, 'rishi@company.com', '2025-02-14'), (203, 'sonia', 'finance', 47000, 'sonia@company.com', '2025-03-20'), (204, 'tara', 'marketing', 43000, 'tara@company.com', '2025-04-25'), (205, 'sudarshan', 'sales', 39000, 'sudarshan@company.com', '2025-05-30'), (206, 'nisha', 'it', 51000, 'nisha@company.com', '2025-06-05'), (207, 'arav', 'finance', 60000, 'arav@company.com', '2025-07-12'), (208, 'pallavi', 'hr', 48000, 'pallavi@company.com', '2025-08-18'), (209, 'shreya', 'marketing', 52000, 'shreya@company.com', '2025-09-22'), (210, 'samar', 'sales', 45000, 'samar@company.com', '2025-10-29');
select * from employees;
select emp_name from employees;
select emp_name, salary from employees;
select * from employees where department = 'it';
select * from employees where department = 'hr';
select * from employees where salary > 50000;
select * from employees where salary < 60000;
select * from employees where salary between 45000 and 60000;
select * from employees where department = 'it' and salary > 50000;
select * from employees where department = 'hr' or department = 'finance';
select * from employees where department <> 'hr';
select * from employees where department in ('it','finance');
select * from employees where emp_name like 's%';
select * from employees where emp_name like '%a';
select * from employees where emp_name like '%ar%';
select distinct department from employees;
select * from employees order by salary asc;
select * from employees order by salary desc;
select * from employees order by emp_name asc;
select * from employees limit 5;
select count(*) from employees;
select sum(salary) from employees;
select avg(salary) from employees;
select max(salary) from employees;
select min(salary) from employees;
select department, count(*) from employees group by department;
select department, sum(salary) from employees group by department;
select department, avg(salary) from employees group by department;
select department from employees group by department having count(*) > 2;
select department from employees group by department order by avg(salary) desc limit 1;
